name: Update GitHub Stats

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update_stats:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Update README with GitHub Stats
        uses: Anmol-Baranwal/awesome-readme-stats@v1
        with:
          gh_token: ${{ secrets.GITHUB_TOKEN }}
          commit_message: "Updated GitHub Stats"
          output_file: "README.md"
