name: Update GitHub Stats

on:
  schedule:
    - cron: '0 0 * * *' # Esegue ogni giorno a mezzanotte
  workflow_dispatch:

jobs:
  update_stats:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Update README with GitHub Stats
        uses: anmol098/waka-readme-stats@master
        with:
          gh_token: ${{ secrets.GITHUB_TOKEN }}
          wakatime_apikey: ${{ secrets.WAKATIME_API_KEY }}
          commit_message: "Updated GitHub Stats"
          output_file: "README.md"
